### PR TITLE
artwork: Add app icon

### PR DESCRIPTION
**Pull request by bragefuglseth**
Adds a fullcolor icon, a symbolic and a logo badge (ideal for e.g. chat room avatars).

## Preview

Preview

### CODE REVIEW

**Comment by bragefuglseth** [comment]
This icon is also made with the name "Delineate" in mind, so I suggest renaming the project to that :slightly_smiling_face:

**Comment by SeaDve** [comment]
Wow, thanks! That looks really great.

> This icon is also made with the name "Delineate" in mind, so I suggest renaming the project to that 🙂

Yep, will do in a separate commit.

**Review by SeaDve — APPROVED** [review]

**Comment by SeaDve** [comment]
@bragefuglseth Hi, sorry to bother you here, but I'd like to ask for permission if I could use the icon on my website, specifically [here](https://seadve.github.io/portfolio/). Thankss

**Comment by bragefuglseth** [comment]
Of course! 😁

**Pull request merged**
